# Site
repository: https://github.com/filippo-bosi/filippo-bosi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Filippo Bosi
title: Robotics Engineer
email: filippo.bosi24@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  filippo-bosi
linkedin_username: filippo-bosi

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
gtm: "GTM-PPLKDV8J"
#gtag: "UA-00000000-0"
#google_analytics: "UA-00000000-0"

about_title: About Me
about_profile_image: images/profile.png
about_content: |
  I am a Robotics Engineering student and innovation enthusiast.
  My top 5 skills are:
    - <mark>ROS/ROS2</mark>
    - <mark>C++</mark>
    - <mark>Gazebo</mark>
    - <mark>RoboDK</mark>
    - <mark>MATLAB&Simulink</mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: <img title="COBOD" width="30" height="30" src="/images/logos/cobod_logo.png"> COBOD International
        sub_title: Robotics Engineer Student Assistant
        caption: Oct 2022 - Present <br />
          Copenhagen, Denmark 🇩🇰
        link: https://cobod.com/
        quote: >
          World leader in 3D construction printing solutions.
        description: |
          <mark>Skills</mark>  Robotics · RoboDK · Robot Operating System (ROS) · Ubuntu · C++ · Gazebo · GitHub
      - layout: left
        title: <img title="LIAM LAB" width="30" height="30" src="/images/logos/liam_lab_logo.jpg"> LIAM LAB
        sub_title: PLC Programmer <br />(BSc Thesis)
        caption: Feb 2021 - Oct 2021 <br />
          Bologna, Italy 🇮🇹
        link: https://www.liamlab.it/
        quote: >
          Industrial research laboratory for the automation of packaging machines.
        description: |
          - Studied importance of virtual commissioning in Industry 4.0.
          - Created algorithm for e-commerce product phasing and buffering in TwinCAT 3.
          - Tested and debugged on packaging machine's digital twin with ISG-Virtuos.
          <br />
          <mark>Skills</mark> Automation · Beckhoff TWINCAT3 · PLC Programming · ISG-Virtuos · IEC 61131-3

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: <img title="DTU" width="30" height="30" src="/images/logos/dtu_logo.png"> DTU - Technical University of Denmark
        sub_title: MSc Electrical Engineering - Automation and Robot Technology
        caption: Feb 2022 - Present <br />
          Lyngby, Denmark 🇩🇰

      - layout: top-middle
        title: <img title="KAIST" width="30" height="30" src="/images/logos/kaist_logo.jpeg"> KAIST - Korea Advanced Institute of Science and Technology
        sub_title: Exchange program - Department of Mechanical Engineering
        caption: Feb 2023 - Jun 2023 <br />
          Daejeon, South Korea 🇰🇷 <br />
          <strong>Activities and societies:</strong> 투 Basketball team

      - layout: top-middle
        title: <img title="UniBo" width="30" height="30" src="/images/logos/unibo_logo.png"> University of Bologna
        sub_title: BSc (Double degree) Automation Engineering
        caption: Sep 2018 - Oct 2021 <br />
          Bologna, Italy 🇮🇹          

      - layout: top-middle
        title: <img title="Tongji" width="30" height="30" src="/images/logos/tongji_logo.png"> Tongji University
        sub_title: BSc (Double degree) Automation Engineering
        caption: Aug 2019 - Feb 2020 <br />
          Shanghai China 🇨🇳
        quote: >
          Winner of the AlmaTong scholarship, awarded to 10 students for a one-year exchange program at Tongji University, Shanghai.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Mapping and Navigation for a Robot Waiter
        additional_links:
          - title: Monte Carlo localization
            icon: fab fa-google-drive
            url: https://drive.google.com/file/d/1cBBfGeurg0WTaOKYNN7qK6yGzdvw7FjA/view
          - title: Final report
            icon: fas fa-file-pdf
            url:  https://drive.google.com/file/d/1UIl7tiNhj9kDIb1ifatpipaPoLxsXANC/view

        sub_title: <img src="https://drive.google.com/uc?export=view&id=1cBBfGeurg0WTaOKYNN7qK6yGzdvw7FjA" width="32%" alt="RRT">&nbsp;&nbsp;&nbsp;<img src="/images/projects/nav2.png" alt="Mapping and Navigation" width="50%">
        quote: >
          This project implements mapping and navigation algorithms for a simulated robot waiter in a coffee shop environment.
        description: | 
          Here, Probabilistic Roadmap (PRM) and Adaptive Monte Carlo Localization (AMCL), along with the Robot Operating System (ROS) 
          and Gazebo simulation, are used to solve the tasks. The TurtleBot3 robot, equipped with a laser distance sensor and camera module, is used for validation.
          Mapping involves teleoperation and frontier-based exploration, generating binary occupancy maps in MATLAB. Localization is 
          performed using a particle filter, and navigation includes evaluating ROS2 Nav2 and implementing a PRM planner in MATLAB.
          <br />
          <mark>Skills</mark> Mobile Robotics · Robot Operating System (ROS) · ROS2 · Ubuntu · Gazebo · MATLAB
        border: weak

      - layout: top-middle
        title: Whole-body dynamics of a quadruped robot for simulation 
        sub_title: <img src="/images/projects/aliengo.png" alt="Aliengo" width="50%">
        quote: >
          Using the Aliengo quadruped robot model, the goal was to compute different parameters with increasing difficulty.
        description: |
          - <strong>Exercise 1:</strong> position of the front-right foot given any joint angles.
          - <strong>Exercise 2:</strong> linear and angular velocity of the front-right foot given any joint angles and joint velocities.
          - <strong>Exercise 3:</strong> mass matrix of the system given the generalized coordinates using Composite Rigid Body Algorithm (CRBA).
          - <strong>Exercise 4:</strong> nonlinearity of the system given the generalized coordinates and generalized velocities using the Recursive Newton-Euler Algorithm (RNEA).
          - <strong>Exercise 5:</strong> generalized acceleration for the given generalized coordinate, velocity, and force using Articulated Body Algorithm (ABA).
          <br />
          <mark>Skills</mark> Robotics · Robot Dynamics · C++ · RaiSim · CMake · GitHub
        additional_links:
          - title: GitHub repo
            icon: fab fa-github
            url: https://github.com/filippo-bosi/ME553_2023
        border: weak

      - layout: top-middle
        title: Sampling-based motion planning algorithms in Python
        sub_title: <img src="https://drive.google.com/uc?export=view&id=1Ugm9P0lDzkU5sWoZUj4w4Kbvps_e_cNO" width="20%" alt="alternative sampling-based algorithm (1.1)">&nbsp;&nbsp;&nbsp;<img src="https://drive.google.com/uc?export=view&id=14lm1dkBNIb7G6PGfRDbXj9jMlpHkUaxQ" width="20%" alt="algorithm exploiting domain knowledge (1.2)">&nbsp;&nbsp;&nbsp;<img src="https://drive.google.com/uc?export=view&id=1dOsIUqIaLRLlCcpyDmYNkjnXz-RlrTMI" width="20%" alt="RRT (1.3)">
        quote: >
          This was the main project of the course "Robot Task and Motion Planning" at KAIST.
        description: This project was intended to make the students truly understand and appreciate why sampling-based motion planning algorithms
          have become the dominant paradigm in robotics. The students were required to implement several sampling-based algorithms
          and answer a series of questions that tested their understanding of motion planning algorithms.
          <br /><br />
          <mark>Skills</mark> Robotics · Motion Planning · Python
        additional_links:
          - title: GitHub repo
            icon: fab fa-github
            url: https://github.com/filippo-bosi/sampling-based-motion-planning
          - title: Final report
            icon: fas fa-file-word
            url: https://docs.google.com/document/d/1iIMVnj3xY7iP46eMXmge3UJtcoLJc9_1y0XWvUjkjMI/view

  - title: Certifications
    layout: list
    content:
    - layout: left
      title: <img title="ETH" width="30" height="30" src="/images/logos/eth_logo.jpg"> ETHx - edX
      sub_title: |
        <a href="https://courses.edx.org/courses/course-v1:ETHx+AMRx+1T2018/5b151c51e8bf47c29d97f8a12369df17/ target="_blank"><b>AMRx: Autonomous Mobile Robots</b></a>
      caption: Jan 2022
      link_text: Certification page
      link: https://courses.edx.org/certificates/c3133303935c440abc8f19278e750823
      quote: >
        An online learning initiative of ETH Zürich
      description:  The objective of this course is to provide the basic concepts and algorithms required to develop mobile robots that act
       autonomously in complex environments. The main emphasis is put on mobile robot locomotion and kinematics, environment perception, 
       probabilistic map based localization and mapping, and motion planning. The lectures and exercises of this course introduce several 
       types of robots such as wheeled robots, legged robots and drones.
    - layout: left
      title: <img title="ETS" width="30" height="30" src="/images/logos/toefl_logo.jpg"> TOEFL iBT
      sub_title: Score 102
      caption: Mar 2021

  - title: A Little More About Me
    layout: text
    content: | 
      When I'm not in work mode, I'm all about the fun stuff! I'm a <mark>home automation</mark> geek, turning living spaces into smart havens. 
      <mark>Robotics</mark> is my jam – building bots and watching them come to life is pure magic. <mark>Basketball</mark> courts and <mark>beach volleyball</mark>
      pitches are my happy places, where teamwork and sunny vibes rule. These interests aren't just hobbies; they're the heart of who I am, bringing balance 
      and excitement to every day.
    
  
# Footer
footer_show_references: true
references_title: References on request

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: filippo-bosi/filippo-bosi.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "lib/",
  "docker-compose.yml",
  ]
